services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  opencv:
    build: ./opencv
    container_name: opencv
    depends_on:
      - mqtt
    environment:
<<<<<<< Updated upstream
      ESP32_IP: "192.168.1.49"
      MJPEG_URL: "http://192.168.1.49:81/stream"
=======
      ESP32_IP: "192.168.1.83"
      MJPEG_URL: "http://192.168.1.83:81/stream"
>>>>>>> Stashed changes
      MQTT_BROKER: "mqtt"
      MQTT_PORT: "1883"
      TOL: "20"
      STEP: "2"
      TOPIC_PAN: "esp32cam/cmd/pan"
      TOPIC_TILT: "esp32cam/cmd/tilt"
      TOPIC_MODE: "esp32cam/cmd/mode"
      STATUS_FACES_TOPIC: "esp32cam/status/faces"
    restart: unless-stopped
  web:
    build: ./web
    container_name: web
    depends_on:
      - mqtt
    environment:
      MQTT_BROKER: "mqtt"
      MQTT_PORT: "1883"
      TOPIC_PAN: "esp32cam/cmd/pan"
      TOPIC_TILT: "esp32cam/cmd/tilt"
      TOPIC_MODE: "esp32cam/cmd/mode"
      STEP: "2"
      PAN_START: "90"
      TILT_START: "90"
      FACES_TOPIC: "esp32cam/status/faces"
    ports:
      - "8080:8080"
    restart: unless-stopped

